/**
 * @file Index.ets
 * @brief Settings feature HAR export barrel
 *
 * Exports the main SettingsComponent from the settings feature module.
 */
export { SettingsComponent } from './src/main/ets/SettingsComponent'
export { SettingsPageRoute } from './src/main/ets/FeatureComponent'
export { SettingsPage } from './src/main/ets/view/SettingsPage'
export { AccountSecurityPage } from './src/main/ets/view/AccountSecurityPage'
export { ChangePasswordPage } from './src/main/ets/view/ChangePasswordPage'
export { WebPage } from './src/main/ets/view/WebPage'
