export class RouteName {
  static readonly AUTH_LOGIN: string = 'auth/Login'
  static readonly SESSION_HOME: string = 'session/Home'
  static readonly TERMINAL_SESSION: string = 'terminal/Session'
  static readonly WORKER_LIST: string = 'worker/List'
  static readonly WORKER_DETAIL: string = 'worker/Detail'
  static readonly SETTINGS: string = 'settings/Page'
  static readonly ACCOUNT_SECURITY: string = 'AccountSecurity'
  static readonly CHANGE_PASSWORD: string = 'ChangePassword'
  static readonly ACTIVATE_WORKER: string = 'ActivateWorker'
}
